import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import clientPromise from "../utils/mongo_init";

export default function Home({ users, projects }) {
	console.log({ users, projects });
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>Salut</div>
		</div>
	);
}

export async function getServerSideProps(context) {
	const client = await clientPromise;

	const db = client.db("enershareSB");

	let users = await db.collection("users").find({}).toArray();
	let projects = await db.collection("projects").find({}).toArray();
	users = JSON.parse(JSON.stringify(users));
	projects = JSON.parse(JSON.stringify(projects));

	return {
		props: { users, projects },
	};
}
